import type { AppConfig } from '../types/app';

export const apps: AppConfig[] = [
  {
    id: 'crescer',
    name: 'Crescer',
    url: 'https://crescerb.vercel.app/',
    icon: 'TrendingUp',
    category: 'Business',
    defaultSize: { width: 1100, height: 720 },
    permissionKey: 'crescer',
    gradient: 'linear-gradient(145deg, #49a8ff, #1f6dff 52%, #8f7cff)',
    accentColor: '#49a8ff',
  },
  {
    id: 'gardenz',
    name: 'Gardenz',
    url: 'https://gardenz.vercel.app/',
    icon: 'Leaf',
    category: 'Tools',
    defaultSize: { width: 1100, height: 720 },
    permissionKey: 'gardenz',
    gradient: 'linear-gradient(145deg, #7df2b7, #10b981 48%, #0891b2)',
    accentColor: '#10b981',
  },
  {
    id: 'criptoHub',
    name: 'Cripto Hub',
    url: 'https://cripto-hub.vercel.app/',
    icon: 'Coins',
    category: 'Crypto',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'criptoHub',
    gradient: 'linear-gradient(145deg, #ffe071, #f59e0b 48%, #ef5da8)',
    accentColor: '#f59e0b',
  },
  {
    id: 'bitrade',
    name: 'Bitrade',
    url: 'https://bitrade-eight.vercel.app/',
    icon: 'BarChart3',
    category: 'Trading',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'bitrade',
    gradient: 'linear-gradient(145deg, #72d7ff, #8b5cf6 52%, #ef5da8)',
    accentColor: '#8b5cf6',
  },
  {
    id: 'trade',
    name: 'Trade',
    url: 'https://trade-eosin-kappa.vercel.app/',
    icon: 'CandlestickChart',
    category: 'Trading',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'trade',
    gradient: 'linear-gradient(145deg, #7dd3fc, #6366f1 50%, #f472b6)',
    accentColor: '#6366f1',
  },
  {
    id: 'betintel',
    name: 'BetIntel',
    url: 'https://betintel-api.vercel.app/',
    icon: 'Trophy',
    category: 'Sports',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'betintel',
    gradient: 'linear-gradient(145deg, #ff7a7a, #ef4444 50%, #ffb84d)',
    accentColor: '#ef4444',
  },
  {
    id: 'yield',
    name: 'Yield',
    url: 'https://yield-two-orcin.vercel.app/',
    icon: 'LineChart',
    category: 'DeFi',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'yield',
    gradient: 'linear-gradient(145deg, #6ee7f9, #06b6d4 48%, #34d399)',
    accentColor: '#06b6d4',
  },
];

export const internalApps = [
  {
    id: 'settings',
    name: 'Ajustes',
    icon: 'Settings',
    defaultSize: { width: 720, height: 540 },
    gradient: 'linear-gradient(145deg, #dbeafe, #60a5fa 48%, #64748b)',
    accentColor: '#60a5fa',
  },
  {
    id: 'admin',
    name: 'Painel Admin',
    icon: 'Shield',
    defaultSize: { width: 860, height: 600 },
    gradient: 'linear-gradient(145deg, #ffe071, #f59e0b 48%, #ef5da8)',
    accentColor: '#f59e0b',
  },
];
