import type { AppConfig } from '../types/app';

export const apps: AppConfig[] = [
  {
    id: 'crescer',
    name: 'Crescer',
    url: 'https://crescerb.vercel.app/',
    icon: 'TrendingUp',
    category: 'Business',
    defaultSize: { width: 1100, height: 720 },
    permissionKey: 'crescer',
    gradient: 'linear-gradient(145deg, #3b82f6, #1d4ed8)',
    accentColor: '#3b82f6',
  },
  {
    id: 'gardenz',
    name: 'Gardenz',
    url: 'https://gardenz.vercel.app/',
    icon: 'Leaf',
    category: 'Tools',
    defaultSize: { width: 1100, height: 720 },
    permissionKey: 'gardenz',
    gradient: 'linear-gradient(145deg, #22c55e, #15803d)',
    accentColor: '#22c55e',
  },
  {
    id: 'criptoHub',
    name: 'Cripto Hub',
    url: 'https://cripto-hub.vercel.app/',
    icon: 'Coins',
    category: 'Crypto',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'criptoHub',
    gradient: 'linear-gradient(145deg, #f59e0b, #b45309)',
    accentColor: '#f59e0b',
  },
  {
    id: 'bitrade',
    name: 'Bitrade',
    url: 'https://bitrade-eight.vercel.app/',
    icon: 'BarChart3',
    category: 'Trading',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'bitrade',
    gradient: 'linear-gradient(145deg, #8b5cf6, #6d28d9)',
    accentColor: '#8b5cf6',
  },
  {
    id: 'trade',
    name: 'Trade',
    url: 'https://trade-eosin-kappa.vercel.app/',
    icon: 'CandlestickChart',
    category: 'Trading',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'trade',
    gradient: 'linear-gradient(145deg, #a855f7, #7c3aed)',
    accentColor: '#a855f7',
  },
  {
    id: 'betintel',
    name: 'BetIntel',
    url: 'https://betintel-api.vercel.app/',
    icon: 'Trophy',
    category: 'Sports',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'betintel',
    gradient: 'linear-gradient(145deg, #ef4444, #b91c1c)',
    accentColor: '#ef4444',
  },
  {
    id: 'yield',
    name: 'Yield',
    url: 'https://yield-two-orcin.vercel.app/',
    icon: 'LineChart',
    category: 'DeFi',
    defaultSize: { width: 1200, height: 760 },
    permissionKey: 'yield',
    gradient: 'linear-gradient(145deg, #06b6d4, #0e7490)',
    accentColor: '#06b6d4',
  },
];

export const internalApps = [
  {
    id: 'settings',
    name: 'Configurações',
    icon: 'Settings',
    defaultSize: { width: 720, height: 540 },
    gradient: 'linear-gradient(145deg, #64748b, #334155)',
    accentColor: '#64748b',
  },
  {
    id: 'admin',
    name: 'Painel Admin',
    icon: 'Shield',
    defaultSize: { width: 860, height: 600 },
    gradient: 'linear-gradient(145deg, #f59e0b, #92400e)',
    accentColor: '#f59e0b',
  },
];
